### ISSUE TITLE
problems with installing

### ISSUE THREAD

**Issue by mariolovric** [david-cortes/costsensitive#3]
Hello,

I have problems with the installation.
I installed Cython and Visual Buildstudio, however there are further issues:

  ----------------------------------------
  Failed building wheel for costsensitive
  Running setup.py clean for costsensitive
Failed to build costsensitive
Installing collected packages: costsensitive
  Running setup.py install for costsensitive ... error
    Complete output from command C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-09n7kkgs\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-y9pf5l92\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\costsensitive
    copying costsensitive\__init__.py -> build\lib.win-amd64-3.6\costsensitive
    running build_ext
    skipping 'costsensitive\vwrapper.c' Cython extension (up-to-date)
    building 'costsensitive._vwrapper' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\costsensitive
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccostsensitive\vwrapper.c /Fobuild\temp.win-amd64-3.6\Release\costsensitive\vwrapper.obj -O2 -fopenmp
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    vwrapper.c
    c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    costsensitive\vwrapper.c(595): fatal error C1083: Cannot open include file: '../src/calcv.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-09n7kkgs\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-y9pf5l92\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-09n7kkgs\costsensitive\

any idea?

**Comment by david-cortes** [comment]
Oh sorry I forgot to include a `MANIFEST.in` file - please try again (version 1.2.3 - can use e.g. `pip install -U costsensitive`).

**Comment by mariolovric** [comment]
tried it now with version 0.1.2.3 - problem perstists

  ----------------------------------------
  Failed building wheel for costsensitive
  Running setup.py clean for costsensitive
Failed to build costsensitive
Installing collected packages: costsensitive
  Running setup.py install for costsensitive ... error
    Complete output from command C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-lb1zzw_k\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-zf5ofrn8\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\costsensitive
    copying costsensitive\__init__.py -> build\lib.win-amd64-3.6\costsensitive
    running build_ext
    skipping 'costsensitive\vwrapper.c' Cython extension (up-to-date)
    building 'costsensitive._vwrapper' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\costsensitive
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccostsensitive\vwrapper.c /Fobuild\temp.win-amd64-3.6\Release\costsensitive\vwrapper.obj /openmp /O2
    vwrapper.c
    c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\user\appdata\local\temp\pip-install-lb1zzw_k\costsensitive\costsensitive\../src/calcv.c(81): error C3036: 'max': invalid operator token in OpenMP 'reduction' clause
    c:\users\user\appdata\local\temp\pip-install-lb1zzw_k\costsensitive\costsensitive\../src/calcv.c(100): error C3015: initialization in OpenMP 'for' statement has improper form
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-lb1zzw_k\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-zf5ofrn8\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-lb1zzw_k\costsensitive\

**Comment by david-cortes** [comment]
Sorry again, didn't realize visual studio didn't support openmp `max` reduction. Fixed now. If that still doesn't work, you can try an older version (0.1 or 0.1.1) which does not have C code, or use `mingw` instead of visual studio, or try it on a different operating sytem; but please leave a message if it still fails to install after this (version 0.1.2.4)

**Comment by mariolovric** [comment]
Problem is persistent with 0.1.2.3 and 0.1.2.4

I managed to install 0.1.1 which is ok!

Thanks for the effort!

**Comment by david-cortes** [comment]
Could you post the error trace like above? (Please add a line before and after with 3 backticks so that it would show as code, i.e. ```` ``` ````)

**Comment by mariolovric** [comment]
```(chemenv) C:\>pip install costsensitive==0.1.2.4
Collecting costsensitive==0.1.2.4
  Using cached https://files.pythonhosted.org/packages/d7/17/aec4f6d311de49310c2759b2def9a7cf57742401f18caf0464270d7ce68a/costsensitive-0.1.2.4.tar.gz
Requirement already satisfied: numpy in c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages (from costsensitive==0.1.2.4) (1.16.2)
Requirement already satisfied: scipy in c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages (from costsensitive==0.1.2.4) (1.2.0)
Requirement already satisfied: joblib>=0.13 in c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages (from costsensitive==0.1.2.4) (0.13.0)
Requirement already satisfied: cython in c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages (from costsensitive==0.1.2.4) (0.29.6)
Building wheels for collected packages: costsensitive
  Running setup.py bdist_wheel for costsensitive ... error
  Complete output from command C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-j2mpd7jl\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\user\AppData\Local\Temp\pip-wheel-6rkftkk0 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\costsensitive
  copying costsensitive\__init__.py -> build\lib.win-amd64-3.6\costsensitive
  running build_ext
  cythoning costsensitive/vwrapper.pyx to costsensitive\vwrapper.c
  C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\user\AppData\Local\Temp\pip-install-j2mpd7jl\costsensitive\costsensitive\vwrapper.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'costsensitive._vwrapper' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\costsensitive
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccostsensitive\vwrapper.c /Fobuild\temp.win-amd64-3.6\Release\costsensitive\vwrapper.obj /O2
  vwrapper.c
  c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  c:\users\user\appdata\local\temp\pip-install-j2mpd7jl\costsensitive\costsensitive\../src/calcv.c(127): fatal error C1004: unexpected end-of-file found
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for costsensitive
  Running setup.py clean for costsensitive
Failed to build costsensitive
Installing collected packages: costsensitive
  Found existing installation: costsensitive 0.1.1
    Uninstalling costsensitive-0.1.1:
      Successfully uninstalled costsensitive-0.1.1
  Running setup.py install for costsensitive ... error
    Complete output from command C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-j2mpd7jl\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-90lm4apa\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\costsensitive
    copying costsensitive\__init__.py -> build\lib.win-amd64-3.6\costsensitive
    running build_ext
    skipping 'costsensitive\vwrapper.c' Cython extension (up-to-date)
    building 'costsensitive._vwrapper' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\costsensitive
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccostsensitive\vwrapper.c /Fobuild\temp.win-amd64-3.6\Release\costsensitive\vwrapper.obj /O2
    vwrapper.c
    c:\users\user\appdata\local\continuum\anaconda3\envs\chemenv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\user\appdata\local\temp\pip-install-j2mpd7jl\costsensitive\costsensitive\../src/calcv.c(127): fatal error C1004: unexpected end-of-file found
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of costsensitive
Command "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\chemenv\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-j2mpd7jl\\costsensitive\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-90lm4apa\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-j2mpd7jl\costsensitive\```

**Comment by david-cortes** [comment]
Please try one last time (version 0.1.2.6).

**Comment by mariolovric** [comment]
Works!!!
Well done!
