### ISSUE TITLE
How do we get other evaluation metrics to run

### ISSUE THREAD

**Issue by emjosh13** [david-cortes/costsensitive#7]
Hi David !
I was wondering, how can we check for the evaluation metrics like precision, recall, f1-score, and AUROC using the cost sensitive library? Based on the documentation, it didn't talk about how to address these. We can only get the accuracy. I'd appreciate your feedback on this. Look forward to hearing from you.

**Comment by david-cortes** [comment]
It doesn't have such functionality, and I'm not familiar with cost-sensitive variations of those metrics.

You can use scikit-learn for those calculations. Although, if you have a binary-classification problem in which it makes sense to maximize that kind of metrics, you probably shouldn't be using `costsensitive` as it'd be the same as weighted binary classification.
